import type { NextPage } from 'next'
import Head from 'next/head'
import { ApolloProvider } from "@apollo/client";
import client from "../apollo-client";
import { Componente } from '../components/componente';
import { CoetesImagen } from '../components/imagencoetes';

const Home: NextPage = () => {
  
  return (
    <ApolloProvider client={client}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='flex w-full justify-center items-center flex-col mt-6'>
          <a href='#'>
            <h1 className='
            font-extrabold text-4xl font-sans uppercase mb-5 border-2 border-indigo-400 rounded-full
            px-6 py-2 hover:text-indigo-400 hover:border-black transition cursor-pointer select-none
            '>titulo de este metodo</h1>
          </a>
          <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5'>
            <CoetesImagen/>
          </div>
            
          <Componente/>
          <button className='
          text-indigo-600 bg-black m-6 p-6 rounded-full hover:text-white 
          hover:bg-indigo-600 cursor-pointer transition
          '>holaa que tal</button>
        </div>
    </ApolloProvider>
    
  )
}

export default Home
